Fixed ESLint errors.
Lambda-School-Labs/startup-grant-database-pt5-fe pull request #30
Opened 2019-11-13 03:31 UTC by jonnytrav

# Description
End to end tests using cypress.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Test A/ end to end testing
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2019-11-13 22:05 UTC, scottschindler approved these changes

2019-11-13 22:05 UTC, scottschindler approved these changes
Good Job, Jonathan!

2019-11-13 22:07 UTC, scottschindler requested changes
Jonathan, it looks like you have a few merge conflicts. Do you mind resolving these before I can merge to master?

2019-11-15 03:02 UTC, tjforeman reviewed
Closing this pull request since the team decided against ESlint

2019-11-15 03:03 UTC, closed without merging